[app]
name = "insulink"

[version]
major = 0
minor = 0
patch = 0
alias = ""

[ai]
default_model  = "gemini-1.5-pro"
fallback_model = "gemini-1.5-flash"
harm_category_dangerous_content = "BLOCK_MEDIUM_AND_ABOVE"
harm_category_harassment = "BLOCK_MEDIUM_AND_ABOVE"
harm_category_hate_speech = "BLOCK_MEDIUM_AND_ABOVE"
harm_category_sexually_explicit = "BLOCK_MEDIUM_AND_ABOVE"
max_output_tokens = 8192
temperature = 0.7
top_k = 40
top_p = 0.95

[container]
backend = "podman"
os = "docker.io/library/debian@sha256:67b30a61dc87758f0caf819646104f29ecbda97d920aaf5edc834128ac8493d3" # bookworm-slim

[repo]
host = "github.com"
user = "ferwoitschach"
name = "insulink"
